---
fixtures:
  repositories:
    auditd:               "git://github.com/simp/pupmod-simp-auditd"
    common:               "git://github.com/simp/pupmod-simp-common"
    compliance_markup:    "git://github.com/trevor-vaughan/pupmod-compliance"
    simplib:              "git://github.com/simp/pupmod-simp-simplib"
    augeasproviders_core:
      repo: "git://github.com/simp/augeasproviders_core"
      branch: "simp-master"
    augeasproviders_grub:
      repo: "git://github.com/simp/augeasproviders_grub"
      branch: "simp-master"
    simpcat:               "git://github.com/simp/pupmod-simp-concat"
    functions:            "git://github.com/simp/pupmod-simp-functions"
    iptables:             "git://github.com/simp/pupmod-simp-iptables"
    logrotate:            "git://github.com/simp/pupmod-simp-logrotate"
    pki:                  "git://github.com/simp/pupmod-simp-pki"
    stdlib:
      repo: "git://github.com/simp/puppetlabs-stdlib"
      branch: "simp-master"
    stunnel:              "git://github.com/simp/pupmod-simp-stunnel"
    tcpwrappers:          "git://github.com/simp/pupmod-simp-tcpwrappers"
    compliance:           "https://github.com/trevor-vaughan/pupmod-compliance"
  symlinks:
    rsyslog: "#{source_dir}"
