---
fixtures:
  repositories:
    concat: https://github.com/simp/puppetlabs-concat
    iptables: https://github.com/simp/pupmod-simp-iptables
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki: https://github.com/simp/pupmod-simp-pki
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    stunnel: https://github.com/simp/pupmod-simp-stunnel
    systemd: https://github.com/simp/puppet-systemd
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    rsyslog: "#{source_dir}"
