---
fixtures:
  repositories:
    auditd:
      repo: https://github.com/simp/pupmod-simp-auditd
    augeasproviders_core:
      repo: https://github.com/simp/augeasproviders_core
    augeasproviders_grub:
      repo: https://github.com/simp/augeasproviders_grub
    concat:
      repo: https://github.com/simp/puppetlabs-concat
    haveged:
      repo: https://github.com/simp/puppet-haveged
    iptables:
      repo: https://github.com/simp/pupmod-simp-iptables
    logrotate:
      repo: https://github.com/simp/pupmod-simp-logrotate
    pki:
      repo: https://github.com/simp/pupmod-simp-pki
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
    stdlib:
      repo: https://github.com/simp/puppetlabs-stdlib
    stunnel:
      repo: https://github.com/simp/pupmod-simp-stunnel
    tcpwrappers:
      repo: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    rsyslog: "#{source_dir}"
