---
fixtures:
  repositories:
    auditd:               "git://github.com/simp/pupmod-simp-auditd"
    common:               "git://github.com/simp/pupmod-simp-common"
    augeasproviders_core: "git://github.com/simp/augeasproviders_core"
    augeasproviders_grub: "git://github.com/simp/augeasproviders_grub"
    concat:               "git://github.com/simp/pupmod-simp-concat"
    functions:            "git://github.com/simp/pupmod-simp-functions"
    iptables:             "git://github.com/simp/pupmod-simp-iptables"
    logrotate:            "git://github.com/simp/pupmod-simp-logrotate"
    pki:                  "git://github.com/simp/pupmod-simp-pki"
    stdlib:               "git://github.com/simp/puppetlabs-stdlib"
    stunnel:              "git://github.com/simp/pupmod-simp-stunnel"
    tcpwrappers:          "git://github.com/simp/pupmod-simp-tcpwrappers"
  symlinks:
    rsyslog: "#{source_dir}"
