<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  client:
    roles:
      - default
      - master
      - client
    platform:   el-8-x86_64
    box:        generic/centos8
    hypervisor: <%= hypervisor %>
  server-1:
    roles:
      - server
    platform:   el-8-x86_64
    box:        generic/centos8
    hypervisor: <%= hypervisor %>
  server-2:
    roles:
      - nextserver
    platform:   el-8-x86_64
    box:        generic/centos8
    hypervisor: <%= hypervisor %>
CONFIG:
  log_level:       verbose
  type:            aio
  vagrant_memsize: 512
  ssh:
    keepalive: true
    keepalive_interval: 10
    keepalive_maxcount: 60
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
