HOSTS:
  client:
    roles:
      - default
      - master
      - client
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  server-1:
    roles:
      - server
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  server-2:
    roles:
      - server
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  server-3:
    roles:
      - failover_server
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
CONFIG:
  log_level:       verbose
  type:            aio
  vagrant_memsize: 256
