HOSTS:
  client:
    roles:
      - default
      - master
      - client
    platform:   el-7-x86_64
    box:        puppetlabs/centos-7.0-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant
  server-1:
    roles:
      - server
    platform:   el-7-x86_64
    box:        puppetlabs/centos-7.0-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant
  server-2:
    roles:
      - server
    platform:   el-7-x86_64
    box:        puppetlabs/centos-7.0-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant
  server-3:
    roles:
      - failover_server
    platform:   el-7-x86_64
    box:        puppetlabs/centos-7.0-64-nocm
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
    hypervisor: vagrant
CONFIG:
  log_level:       verbose
  type:            foss
  vagrant_memsize: 384
